export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FORCAST_SUCCESS = "FETCH_FORCAST_SUCCESS";
export const FETCH_FAILED = "FETCH_FAILED";
